#!/bin/bash

source pyenv/bin/activate
#uwsgi --emperor config
uwsgi --http :5005 --chdir src/controllers --wsgi-file app.py --thunder-lock --enable-threads --callable app --touch-reload app.py --optimize 2





